apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: canteen-service
  name: canteen-service
spec:
  type: ClusterIP
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    io.kompose.service: canteen-service
