apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: purvakamerkarjj5499079/mealmonitor-eurekaserver:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          name: mealmontor-eureka-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
