apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: LoadBalancer
  loadBalancerIP: 34.59.41.93
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: gateway
