apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: moderation-service
  name: moderation-service
spec:
  type: ClusterIP
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    io.kompose.service: moderation-service

