apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  type: LoadBalancer
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    io.kompose.service: zipkin
